#!/bin/sh
~/.local/bin/streamlit run /var/www/html/app.py  # systemdから実行するため、streamlitの実行ファイルはフルパスで指定
[ec2-user@ip-10-0-21-63 my-app]$ cat appspec.yml 
version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/my-app
hooks:
  BeforeInstall:
    - location: scripts/stop_server.sh
  AfterInstall:
    - location: scripts/start_server.sh
file_exists_behavior: OVERWRITE